modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory
issueTrackerURL="https://www.google.com"
authors="lazynessmind"
[[mods]] #mandatory
modId="blockactions"
version="0.0.2-1.15.2" #mandatory
displayName="Block Actions"
description='''
Block that reproduce player actions.
'''